# Generated by Django 2.1.5 on 2019-02-07 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gugugu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='room',
        ),
    ]
