# Generated by Django 2.1.5 on 2019-02-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gugugu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='nickname',
            field=models.TextField(verbose_name='Nickname'),
        ),
    ]
