# Generated by Django 2.1.5 on 2019-02-02 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gugugu', '0002_auto_20190202_2128'),
        ('gugugu', '0002_auto_20190202_2155'),
    ]

    operations = [
    ]
