# Generated by Django 2.1.5 on 2019-02-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gugugu', '0004_auto_20190204_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='date_deactivated',
            field=models.DateTimeField(default=True, verbose_name='Date Deactivated'),
        ),
    ]
