# Generated by Django 2.1.7 on 2019-02-16 07:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gugugu', '0005_auto_20190209_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date Created')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claps', to='gugugu.Member')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claps', to='gugugu.Message')),
            ],
        ),
    ]
