# Generated by Django 2.1.5 on 2019-02-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gugugu', '0005_auto_20190205_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='date_deactivated',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date Deactivated'),
        ),
    ]
