# Generated by Django 2.1.7 on 2019-02-16 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gugugu', '0006_clap'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='date_claps_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Claps Updated'),
        ),
        migrations.AddField(
            model_name='room',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='session_key',
            field=models.CharField(max_length=255, null=True, verbose_name='Session Key'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('room', 'user'), ('room', 'name')},
        ),
    ]
