# Generated by Django 2.1.5 on 2019-02-05 04:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gugugu', '0006_auto_20190205_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='room',
            name='date_polled',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Last Polled'),
        ),
        migrations.AlterField(
            model_name='room',
            name='date_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Updated'),
        ),
    ]
