# Generated by Django 2.1.7 on 2019-02-19 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gugugu', '0007_auto_20190216_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalkRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('department', models.CharField(max_length=25)),
                ('student_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('interest', models.CharField(max_length=100)),
                ('career_path', models.CharField(max_length=100)),
                ('inquiry', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('room', 'user')},
        ),
    ]
