# Generated by Django 2.1.7 on 2019-02-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gugugu', '0008_auto_20190220_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talkregistration',
            name='inquiry',
        ),
    ]
