# Generated by Django 2.1.7 on 2019-02-19 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gugugu', '0008_talkregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talkregistration',
            name='inquiry',
        ),
        migrations.AlterField(
            model_name='talkregistration',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('room', 'user')},
        ),
    ]
